### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [CorantGmbH/aioairq#3]
It would be very helpful if you could tag releases as well again. This would enable distributions who want to fetch the source from GitHub instead of PyPI.

Thanks

**Comment by Sibgatulin** [comment]
Hi Fabian! Thanks for pointing it out, I completely forgot to. I tagged every version bump and pushed respective tags. Would this already be sufficient for the purpose?

Truth be told, latest `aioairq` version numbers had been advancing rapidly (almost per commit), driven by simultaneous development of the home assistant integration, using this module. I am thus somewhat hesitant to create releases for each of the pushed tags / versions published to PyPI not to overwhelm the list of releases here. I am hoping, in the nearest future the release pace will normalise and I'll put out an actual github release alongside with the git tag. 

If, however, a release is preferred over a tag for the purpose of source fetching, I gladly create a release for the latest version.

**Comment by fabaff** [comment]
For the NixOS packages we are pulling the source from GitHub. Usually the Gentoo packagers also prefer to get the source from the upstream location.

Thus, tagging is sufficient.

**Comment by Sibgatulin** [comment]
Great, thanks for the explanation!
